sonar.projectKey=distributed-job-scheduler
sonar.projectName=Distributed Job Scheduler
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.git/**,backend/database/migrations/**,**/static/**
sonar.python.version=3.11
sonar.tests=backend/app/tests

# Backend
sonar.python.xunit.reportPath=backend/test-reports/pytest.xml
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.sourceEncoding=UTF-8
