sonar.sources=backend/app,frontend
sonar.tests=backend/tests,backend/app/tests
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=README.md,frontend/README.md,frontend/FRONTEND_GUIDE.md,backend/database/**,backend/scripts/**,backend/tests/**,backend/app/tests/**,deploy/**,k3s/**,.github/**,frontend/k8s/**,frontend/db.sqlite3,frontend/ui/templates/**,frontend/ui/static/**
sonar.test.exclusions=backend/tests/**,backend/app/tests/**
sonar.coverage.exclusions=backend/app/tests/**,backend/tests/**,frontend/**,backend/app/presentation/dtos/**
sonar.cpd.exclusions=frontend/**,backend/app/tests/**,backend/tests/**
