sonar.projectKey=distributed-job-scheduler
sonar.projectName=Distributed Job Scheduler
sonar.projectVersion=1.0
sonar.host.url=http://sonarqube:9000
sonar.token=squ_200f3ece02d4266991b0e00003d3733a1d3ef747

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.git/**,backend/database/migrations/**,**/static/**
sonar.python.version=3.11

# Backend
sonar.python.xunit.reportPath=backend/test-reports/*.xml
sonar.python.coverage.reportPaths=backend/coverage.xml

# Frontend
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
