apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  imagePullSecrets:
  - name: registry-secret
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: registry.git.hsnl.tw/native_cloud/distributed_job_scheduler/backend
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "app.services.scheduler_loop"]
        envFrom:
        - secretRef:
            name: job-scheduler-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  imagePullSecrets:
  - name: registry-secret
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: registry.git.hsnl.tw/native_cloud/distributed_job_scheduler/backend
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "app.services.worker_loop"]
        env:
        - name: WORKER_ID
          value: "worker-k8s-1"
        envFrom:
        - secretRef:
            name: job-scheduler-secret
