-- Migration 006: remove fixed seed data.
--
-- The production project should not ship default accounts or default jobs.
-- Users must register through the API so password_hash is generated by bcrypt.

DELETE FROM job_dependencies
WHERE id = '40000000-0000-0000-0000-000000000001'
   OR job_id IN (
        '10000000-0000-0000-0000-000000000001',
        '10000000-0000-0000-0000-000000000002'
   )
   OR depends_on_job_id IN (
        '10000000-0000-0000-0000-000000000001',
        '10000000-0000-0000-0000-000000000002'
   );

DELETE FROM job_logs
WHERE id IN (
    '30000000-0000-0000-0000-000000000001',
    '30000000-0000-0000-0000-000000000002'
)
   OR job_run_id IN (
        '20000000-0000-0000-0000-000000000001',
        '20000000-0000-0000-0000-000000000002'
   );

DELETE FROM job_runs
WHERE id IN (
    '20000000-0000-0000-0000-000000000001',
    '20000000-0000-0000-0000-000000000002'
)
   OR job_id IN (
        '10000000-0000-0000-0000-000000000001',
        '10000000-0000-0000-0000-000000000002'
   );

DELETE FROM jobs
WHERE id IN (
    '10000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000002'
)
   OR task_name IN ('call-health-api', 'run-cleanup-script');

DELETE FROM users
WHERE id IN (
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000002'
);
